version: '3.9'

services:
  # Backend API Service
  api:
    build:
      context: ./PropeloService
      dockerfile: Dockerfile
    container_name: propelo-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=PropeloDb;User=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - db
    networks:
      - propelo-network

  # Database Service
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: propelo-db
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - propelo-network

  # Frontend Service
  frontend:
    build:
      context: ./propelo-front
      dockerfile: Dockerfile
    container_name: propelo-frontend
    ports:
      - "3000:80"  # Map host port 3000 to container port 80
    depends_on:
      - api
    networks:
      - propelo-network

volumes:
  sql_data:

networks:
  propelo-network:
    driver: bridge