version: '3.9'

services:
  # Nginx Reverse Proxy Service
  nginx:
    image: nginx:alpine
    container_name: propelo-nginx
    ports:
      - "80:80"
      - "443:443"  # Reserved for future SSL
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl  # For SSL certificates
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - api
    networks:
      - propelo-network

  # Backend API Service
  api:
    build:
      context: ./PropeloService
      dockerfile: Dockerfile
    container_name: propelo-api
    expose:
      - "8080"
      - "8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=PropeloDb;User=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - db
    networks:
      - propelo-network

  # Database Service
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: propelo-db
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - propelo-network

  # Frontend Service (now internal only)
  frontend:
    build:
      context: ./propelo-front
      dockerfile: Dockerfile
    container_name: propelo-frontend
    expose:
      - "80"  # Expose internally only
    volumes:
      - ./propelo-front/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - propelo-network

volumes:
  sql_data:

networks:
  propelo-network:
    driver: bridge